---

- name: "Create directory for ES repo tarball inside backup_path"
  file:
    path: "{{ backup_path }}/es"
    state: "directory"

- name: "create tarball of the ES repo"
  command: "tar -zcf {{ backup_path }}/es/es-repo.tgz ."
  args:
    chdir: "{{ maint_es_repo_path }}"
    warn: false     # avoid the "Consider using the unarchive module" warning
